humhub:
        build: .
        ports:
                - "40080:80"
        container_name: humhub
        volumes:
                - /srv/docker/humhub/mysql/etc:/etc/mysql:Z
                - /srv/docker/humhub/mysql/db:/var/lib/mysql:Z
                - /srv/docker/humhub/app/uploads:/app/uploads:Z
                - /srv/docker/humhub/app/assets:/app/assets:Z
